name: react_stream
version: 0.0.1
description: A library useful for applications or for sharing on pub.dartlang.org.
dependencies:
  observe: any
#  react: any
  react:
    path: /Users/korsvanloon/dart/react-dart
dev_dependencies:
  unittest: any
